apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: recommendationservice
  namespace: app
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationservice
  updatePolicy:
    updateMode: "Off"        # observe + recommend only